/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiConversationsRouteImport } from './routes/api.conversations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated.chat.index'
import { Route as ApiSettingsModelRouteImport } from './routes/api.settings.model'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api.projects.$projectId'
import { Route as ApiHealthReadyRouteImport } from './routes/api.health.ready'
import { Route as ApiHealthLiveRouteImport } from './routes/api.health.live'
import { Route as ApiConversationsConversationIdRouteImport } from './routes/api.conversations.$conversationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated.chat.$conversationId'
import { Route as ApiProjectsProjectIdDocumentsRouteImport } from './routes/api.projects.$projectId.documents'
import { Route as ApiConversationsConversationIdRegenerateRouteImport } from './routes/api.conversations.$conversationId.regenerate'
import { Route as ApiConversationsConversationIdMessagesRouteImport } from './routes/api.conversations.$conversationId.messages'
import { Route as ApiConversationsConversationIdGenerateRouteImport } from './routes/api.conversations.$conversationId.generate'
import { Route as ApiProjectsProjectIdDocumentsDocumentIdRouteImport } from './routes/api.projects.$projectId.documents.$documentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiSettingsModelRoute = ApiSettingsModelRouteImport.update({
  id: '/api/settings/model',
  path: '/api/settings/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdRoute =
  ApiConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiProjectsProjectIdDocumentsRoute =
  ApiProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiConversationsConversationIdRegenerateRoute =
  ApiConversationsConversationIdRegenerateRouteImport.update({
    id: '/regenerate',
    path: '/regenerate',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdMessagesRoute =
  ApiConversationsConversationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdGenerateRoute =
  ApiConversationsConversationIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiProjectsProjectIdDocumentsDocumentIdRoute =
  ApiProjectsProjectIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiProjectsProjectIdDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/settings/model': typeof ApiSettingsModelRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/conversations/$conversationId/regenerate': typeof ApiConversationsConversationIdRegenerateRoute
  '/api/projects/$projectId/documents': typeof ApiProjectsProjectIdDocumentsRouteWithChildren
  '/api/projects/$projectId/documents/$documentId': typeof ApiProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/settings/model': typeof ApiSettingsModelRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/conversations/$conversationId/regenerate': typeof ApiConversationsConversationIdRegenerateRoute
  '/api/projects/$projectId/documents': typeof ApiProjectsProjectIdDocumentsRouteWithChildren
  '/api/projects/$projectId/documents/$documentId': typeof ApiProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/settings/model': typeof ApiSettingsModelRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
  '/api/conversations/$conversationId/regenerate': typeof ApiConversationsConversationIdRegenerateRoute
  '/api/projects/$projectId/documents': typeof ApiProjectsProjectIdDocumentsRouteWithChildren
  '/api/projects/$projectId/documents/$documentId': typeof ApiProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/projects'
    | '/settings'
    | '/api/conversations'
    | '/api/projects'
    | '/chat/$conversationId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/projects/$projectId'
    | '/api/settings/model'
    | '/chat/'
    | '/projects/'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
    | '/api/conversations/$conversationId/regenerate'
    | '/api/projects/$projectId/documents'
    | '/api/projects/$projectId/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/settings'
    | '/api/conversations'
    | '/api/projects'
    | '/chat/$conversationId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/projects/$projectId'
    | '/api/settings/model'
    | '/chat'
    | '/projects'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
    | '/api/conversations/$conversationId/regenerate'
    | '/api/projects/$projectId/documents'
    | '/api/projects/$projectId/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/chat'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/api/conversations'
    | '/api/projects'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/projects/$projectId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/projects/$projectId'
    | '/api/settings/model'
    | '/_authenticated/chat/'
    | '/_authenticated/projects/'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
    | '/api/conversations/$conversationId/regenerate'
    | '/api/projects/$projectId/documents'
    | '/api/projects/$projectId/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiSettingsModelRoute: typeof ApiSettingsModelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/settings/model': {
      id: '/api/settings/model'
      path: '/api/settings/model'
      fullPath: '/api/settings/model'
      preLoaderRoute: typeof ApiSettingsModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId': {
      id: '/api/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/api/conversations/$conversationId'
      preLoaderRoute: typeof ApiConversationsConversationIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/projects/$projectId/documents': {
      id: '/api/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/api/projects/$projectId/documents'
      preLoaderRoute: typeof ApiProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/conversations/$conversationId/regenerate': {
      id: '/api/conversations/$conversationId/regenerate'
      path: '/regenerate'
      fullPath: '/api/conversations/$conversationId/regenerate'
      preLoaderRoute: typeof ApiConversationsConversationIdRegenerateRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/messages': {
      id: '/api/conversations/$conversationId/messages'
      path: '/messages'
      fullPath: '/api/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/generate': {
      id: '/api/conversations/$conversationId/generate'
      path: '/generate'
      fullPath: '/api/conversations/$conversationId/generate'
      preLoaderRoute: typeof ApiConversationsConversationIdGenerateRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/projects/$projectId/documents/$documentId': {
      id: '/api/projects/$projectId/documents/$documentId'
      path: '/$documentId'
      fullPath: '/api/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof ApiProjectsProjectIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdDocumentsRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiConversationsConversationIdRouteChildren {
  ApiConversationsConversationIdGenerateRoute: typeof ApiConversationsConversationIdGenerateRoute
  ApiConversationsConversationIdMessagesRoute: typeof ApiConversationsConversationIdMessagesRoute
  ApiConversationsConversationIdRegenerateRoute: typeof ApiConversationsConversationIdRegenerateRoute
}

const ApiConversationsConversationIdRouteChildren: ApiConversationsConversationIdRouteChildren =
  {
    ApiConversationsConversationIdGenerateRoute:
      ApiConversationsConversationIdGenerateRoute,
    ApiConversationsConversationIdMessagesRoute:
      ApiConversationsConversationIdMessagesRoute,
    ApiConversationsConversationIdRegenerateRoute:
      ApiConversationsConversationIdRegenerateRoute,
  }

const ApiConversationsConversationIdRouteWithChildren =
  ApiConversationsConversationIdRoute._addFileChildren(
    ApiConversationsConversationIdRouteChildren,
  )

interface ApiConversationsRouteChildren {
  ApiConversationsConversationIdRoute: typeof ApiConversationsConversationIdRouteWithChildren
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsConversationIdRoute:
    ApiConversationsConversationIdRouteWithChildren,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiProjectsProjectIdDocumentsRouteChildren {
  ApiProjectsProjectIdDocumentsDocumentIdRoute: typeof ApiProjectsProjectIdDocumentsDocumentIdRoute
}

const ApiProjectsProjectIdDocumentsRouteChildren: ApiProjectsProjectIdDocumentsRouteChildren =
  {
    ApiProjectsProjectIdDocumentsDocumentIdRoute:
      ApiProjectsProjectIdDocumentsDocumentIdRoute,
  }

const ApiProjectsProjectIdDocumentsRouteWithChildren =
  ApiProjectsProjectIdDocumentsRoute._addFileChildren(
    ApiProjectsProjectIdDocumentsRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdDocumentsRoute: typeof ApiProjectsProjectIdDocumentsRouteWithChildren
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdDocumentsRoute:
    ApiProjectsProjectIdDocumentsRouteWithChildren,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

interface ApiProjectsRouteChildren {
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiSettingsModelRoute: ApiSettingsModelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
