/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConversationsRouteImport } from './routes/api.conversations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated.chat.index'
import { Route as ApiHealthReadyRouteImport } from './routes/api.health.ready'
import { Route as ApiHealthLiveRouteImport } from './routes/api.health.live'
import { Route as ApiConversationsConversationIdRouteImport } from './routes/api.conversations.$conversationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated.chat.$conversationId'
import { Route as ApiConversationsConversationIdMessagesRouteImport } from './routes/api.conversations.$conversationId.messages'
import { Route as ApiConversationsConversationIdGenerateRouteImport } from './routes/api.conversations.$conversationId.generate'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsConversationIdRoute =
  ApiConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiConversationsConversationIdMessagesRoute =
  ApiConversationsConversationIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)
const ApiConversationsConversationIdGenerateRoute =
  ApiConversationsConversationIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiConversationsConversationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/$conversationId': typeof ApiConversationsConversationIdRouteWithChildren
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/conversations/$conversationId/generate': typeof ApiConversationsConversationIdGenerateRoute
  '/api/conversations/$conversationId/messages': typeof ApiConversationsConversationIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/settings'
    | '/api/conversations'
    | '/chat/$conversationId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/chat/'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/settings'
    | '/api/conversations'
    | '/chat/$conversationId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/chat'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/chat'
    | '/_authenticated/settings'
    | '/api/conversations'
    | '/_authenticated/chat/$conversationId'
    | '/api/auth/$'
    | '/api/conversations/$conversationId'
    | '/api/health/live'
    | '/api/health/ready'
    | '/_authenticated/chat/'
    | '/api/conversations/$conversationId/generate'
    | '/api/conversations/$conversationId/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$conversationId': {
      id: '/api/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/api/conversations/$conversationId'
      preLoaderRoute: typeof ApiConversationsConversationIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/conversations/$conversationId/messages': {
      id: '/api/conversations/$conversationId/messages'
      path: '/messages'
      fullPath: '/api/conversations/$conversationId/messages'
      preLoaderRoute: typeof ApiConversationsConversationIdMessagesRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
    '/api/conversations/$conversationId/generate': {
      id: '/api/conversations/$conversationId/generate'
      path: '/generate'
      fullPath: '/api/conversations/$conversationId/generate'
      preLoaderRoute: typeof ApiConversationsConversationIdGenerateRouteImport
      parentRoute: typeof ApiConversationsConversationIdRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiConversationsConversationIdRouteChildren {
  ApiConversationsConversationIdGenerateRoute: typeof ApiConversationsConversationIdGenerateRoute
  ApiConversationsConversationIdMessagesRoute: typeof ApiConversationsConversationIdMessagesRoute
}

const ApiConversationsConversationIdRouteChildren: ApiConversationsConversationIdRouteChildren =
  {
    ApiConversationsConversationIdGenerateRoute:
      ApiConversationsConversationIdGenerateRoute,
    ApiConversationsConversationIdMessagesRoute:
      ApiConversationsConversationIdMessagesRoute,
  }

const ApiConversationsConversationIdRouteWithChildren =
  ApiConversationsConversationIdRoute._addFileChildren(
    ApiConversationsConversationIdRouteChildren,
  )

interface ApiConversationsRouteChildren {
  ApiConversationsConversationIdRoute: typeof ApiConversationsConversationIdRouteWithChildren
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsConversationIdRoute:
    ApiConversationsConversationIdRouteWithChildren,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
